# Generated by Django 3.2 on 2021-04-15 11:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0005_application'),
        ('userprofile', '0004_conversationmesage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConversationMesage',
            new_name='ConversationMessage',
        ),
    ]
