# Generated by Django 3.2 on 2021-06-30 23:16

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_auto_20210616_2109'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('status', django.db.models.manager.Manager()),
            ],
        ),
    ]
