# Generated by Django 3.2 on 2021-04-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(default='Default name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='company_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='company_country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='company_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='company_size',
            field=models.CharField(choices=[('size_1_9', '1-9'), ('size_10_49', '10-49'), ('size_50_99', '50-99'), ('size_100', '100')], default='size_1_9', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='company_zipcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
