# Generated by Django 3.2 on 2021-04-16 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_job_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='company',
            new_name='company_name',
        ),
    ]
