# Generated by Django 3.2 on 2021-04-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_alter_job_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='short_description',
            field=models.TextField(default='Default'),
            preserve_default=False,
        ),
    ]
